estuary/airbyte

airbyte-integrations/connectors/source-google-sheets/google_sheets_source/google_sheets_source.py
airbyte-integrations/connectors/source-google-sheets/google_sheets_source/helpers.py
airbyte-integrations/connectors/source-google-sheets/unit_tests/test_helpers.py

- `row_id` is now part of the collection properties and is set as the default primary key

source-google-sheets: add row_id to data and use it as primary key

---

airbyte-integrations/connectors/source-facebook-marketing/Dockerfile
airbyte-integrations/connectors/source-facebook-marketing/integration_tests/configured_catalog.json
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/streams.py
airbyte-integrations/connectors/source-facebook-marketing/unit_tests/test_client.py
local-build-push.sh

Revert "facebook: unlimited retries in case of ratelimit errors"

---

airbyte-integrations/connectors/source-google-sheets/google_sheets_source/helpers.py

- Improve the error message when failing to read service account JSON
[Solves #486](https://github.com/estuary/flow/issues/486)

google-sheets: better error message when failing to read SA json

---

.github/workflows/connectors.yml
airbyte-integrations/connectors/source-amplitude/Dockerfile
airbyte-integrations/connectors/source-exchange-rates/Dockerfile
airbyte-integrations/connectors/source-facebook-marketing/Dockerfile
airbyte-integrations/connectors/source-github/Dockerfile
airbyte-integrations/connectors/source-gitlab/Dockerfile
airbyte-integrations/connectors/source-google-analytics-v4/Dockerfile
airbyte-integrations/connectors/source-google-sheets/Dockerfile
airbyte-integrations/connectors/source-hubspot/Dockerfile
airbyte-integrations/connectors/source-hubspot/integration_tests/invalid_config.json
airbyte-integrations/connectors/source-hubspot/source_hubspot/source.py
airbyte-integrations/connectors/source-hubspot/source_hubspot/spec.yaml
airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py
airbyte-integrations/connectors/source-hubspot/unit_tests/conftest.py
airbyte-integrations/connectors/source-hubspot/unit_tests/test_source.py
airbyte-integrations/connectors/source-intercom/Dockerfile
airbyte-integrations/connectors/source-mailchimp/Dockerfile
airbyte-integrations/connectors/source-stripe/Dockerfile
airbyte-integrations/connectors/source-zendesk-support/Dockerfile
buildSrc/src/main/groovy/airbyte-python.gradle

- deprecate API Key credentials in favour of Private App Credentials with access_token

source-hubspot: deprecate api key in favour of private app access_token

---

airbyte-integrations/connectors/source-google-analytics-v4/source_google_analytics_v4/spec.json

add oauth spec to google-analytics-v4

google-analytics-v4: add oauth spec

---

airbyte-to-flow/src/interceptors/fix_document_schema.rs

This is blocking https://github.com/estuary/connectors/pull/378 since our mysql and postgres connectors generate advanced schemas with `refs` and `allOf`, etc.
Since these connectors actually provide compatible schemas, we don't need to fix them. I just addressed the case of advanced operators `allOf`, `anyOf` and `not` by skipping them and printing a warning.

airbyte-to-flow: address advanced cases of fix document schema

---

airbyte-integrations/connectors/source-bing-ads/oauth2.patch.json
airbyte-integrations/connectors/source-facebook-marketing/oauth2.patch.json
airbyte-integrations/connectors/source-github/oauth2.patch.json
airbyte-integrations/connectors/source-google-ads/oauth2.patch.json
airbyte-integrations/connectors/source-google-analytics-data-api/oauth2.patch.json
airbyte-integrations/connectors/source-google-analytics-v4/oauth2.patch.json
airbyte-integrations/connectors/source-google-search-console/oauth2.patch.json
airbyte-integrations/connectors/source-google-sheets/oauth2.patch.json
airbyte-integrations/connectors/source-hubspot/oauth2.patch.json
airbyte-integrations/connectors/source-intercom/oauth2.patch.json
airbyte-integrations/connectors/source-linkedin-ads/oauth2.patch.json
airbyte-integrations/connectors/source-mailchimp/oauth2.patch.json
airbyte-integrations/connectors/source-notion/oauth2.patch.json
airbyte-integrations/connectors/source-surveymonkey/oauth2.patch.json
airbyte-integrations/connectors/source-tiktok-marketing/oauth2.patch.json

needs https://github.com/estuary/flow/pull/833

oauth: update all helper tag usages to block helpers

---

.github/workflows/connectors.yml

Revert "ci: gh-webhook call"

---

airbyte-integrations/connectors/source-salesforce/documentation_url.patch.json
airbyte-integrations/connectors/source-salesforce/spec.patch.json

solves https://github.com/estuary/airbyte/issues/107

source-salesforce: fix description and add documentation_url

---

airbyte-integrations/connectors/source-surveymonkey/Dockerfile
airbyte-integrations/connectors/source-tiktok-marketing/Dockerfile

Updating these to get the images working with the latest protocol changes

source-{surveymonkey,tiktok-marketing}: change airbyte-to-flow image pin to dev

---

airbyte-to-flow/src/interceptors/fix_document_schema.rs
airbyte-to-flow/src/interceptors/normalize.rs

- More normalizations we have found we need. More specifically seen in Jira capture.

atf: remove "xml" and normalize "int32"/"int64" formats to "integer"

---

.github/workflows/connectors.yml

The "install psql" step wasn't working anymore, so I copied [how it's done in the connectors repo](https://github.com/estuary/connectors/blob/62954447d977e053807b112b22a7de1158e914ac/.github/workflows/ci.yaml#LL248C15-L250C38) which seems to get it working again.

update psql installation step

---

airbyte-to-flow/src/interceptors/normalize.rs

atf: add another format for date-time normalization (instagram)

---

airbyte-integrations/connectors/source-oracle/spec.patch.json

- Some fixes to make the form render better

oracle: form fixes

---

airbyte-integrations/connectors/source-hubspot/streams/engagements_emails.patch.json

Also applied this to customer's workload and it's running without errors so far 👍

fix: Update `source-hubspot`'s `engagements_emails` stream

---

airbyte-integrations/third-party/gjbakerross/README.md
airbyte-integrations/third-party/gjbakerross/airbyte-source-criteo/Dockerfile
airbyte-integrations/third-party/gjbakerross/airbyte-source-kelkoo/Dockerfile

NOTE: These depend on `ghcr.io/estuary/gjbakerross/source-criteo`/`source-kelkoo` which are built from dockerfiles in the upstream repos using the following command:
```
docker buildx build --no-cache --platform linux/amd64 https://github.com/gjbakerross/airbyte-source-criteo.git -t ghcr.io/estuary/gjbakerross/source-criteo:dev --push
```

Add third party connectors `source-kelkoo` and `source-criteo`

---

airbyte-integrations/connectors/source-google-analytics-data-api/Dockerfile

This is the latest MIT version of the connector

Update google-analytics-data-api Dockerfile

---

airbyte-to-flow/Cargo.lock
airbyte-to-flow/Cargo.toml
airbyte-to-flow/src/interceptors/airbyte_source_interceptor.rs
airbyte-to-flow/src/libs/stream.rs

See https://github.com/estuary/flow/pull/1104

use disable for handling selected streams

---

airbyte-integrations/connectors/source-iterable/streams/email_bounce.pk.json
airbyte-integrations/connectors/source-iterable/streams/email_click.pk.json
airbyte-integrations/connectors/source-iterable/streams/email_complaint.pk.json
airbyte-integrations/connectors/source-iterable/streams/email_open.pk.json
airbyte-integrations/connectors/source-iterable/streams/email_send.pk.json
airbyte-integrations/connectors/source-iterable/streams/email_send_skip.pk.json
airbyte-integrations/connectors/source-iterable/streams/email_unsubscribe.pk.json

Missing quotations for Iterable streams

Fixing iterable stream pks

---

airbyte-integrations/connectors/source-aircall/spec.patch.json

Issue reference: https://github.com/estuary/connectors/issues/995

Aircall spec start date date-time formatting

---

airbyte-integrations/connectors/source-google-search-console/streams/search_analytics_all_fields.patch.json
airbyte-integrations/connectors/source-google-search-console/streams/search_analytics_by_country.patch.json
airbyte-integrations/connectors/source-google-search-console/streams/search_analytics_by_date.patch.json
airbyte-integrations/connectors/source-google-search-console/streams/search_analytics_by_device  Key.patch.json
airbyte-integrations/connectors/source-google-search-console/streams/search_analytics_by_page.patch.json
airbyte-integrations/connectors/source-google-search-console/streams/search_analytics_by_query.patch.json

Removing multiples from the Google Search Console schema.

Dyaffe patch 3

---

airbyte-integrations/connectors/source-mixpanel/streams/cohort_members.patch.json
airbyte-integrations/connectors/source-mixpanel/streams/engage.patch.json

Fixing required fields for cohort_members and engage streams

Bad JSON schema fix

---

airbyte-integrations/connectors/source-mixpanel/streams/cohort_members.patch.json
airbyte-integrations/connectors/source-mixpanel/streams/engage.patch.json

Cohort_members and Engage stream  keyword fixes

Mixpanel patch

---

airbyte-integrations/connectors/source-tiktok-marketing/Dockerfile

Adding delete functionality for ads, ad_groups and campaigns

Version bump to 4.0.0, includes deletes

---

airbyte-integrations/connectors/source-mixpanel/streams/engage.patch.json

Fixed typo in Engage stream

---

airbyte-integrations/connectors/source-mixpanel/streams/engage.patch.json

MixPanel: updating transactions field for Engage stream

---

airbyte-integrations/connectors/source-mixpanel/Dockerfile

Improvements rate limits, uses exponential backoff

upgrading Mixpanel to 0.1.36

---

airbyte-integrations/connectors/source-mixpanel/Dockerfile

Revert "upgrading Mixpanel to 0.1.36"

---

airbyte-integrations/connectors/source-tiktok-marketing/Dockerfile

Revert "Version bump to 4.0.0, includes deletes"

---

airbyte-to-flow/Cargo.lock

Updates the Flow protocol references we are using in ATF to the latest.
Part of the planned changed https://github.com/estuary/connectors/issues/1721

atf: update protocols

---

airbyte-integrations/connectors/source-braze/Dockerfile

Bumping Braze version to the latest build

Bumping version to 0.4.1

---

airbyte-integrations/connectors/source-braze/Dockerfile

Revert "Bumping version to 0.4.1"

---

airbyte-integrations/connectors/source-instagram/Dockerfile

Upgrading Instagram to 3.1.8
