airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/source.py, airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/spec.py, airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_streams.py
- Some of the configuration parameters are arrays of enums, and those enums did not have any specific type associated with them, because they were dynamically created.
- This PR ensures that the enums are considered to be of type string
=> source-facebook-marketing: fix config enum types to be string

.github/workflows/connectors.yml, airbyte-to-flow/README.md, airbyte-to-flow/src/errors.rs, airbyte-to-flow/src/interceptors/airbyte_source_interceptor.rs, airbyte-to-flow/src/interceptors/fix_document_schema.rs, airbyte-to-flow/src/interceptors/mod.rs
- Automatically fix document schema of streams by ensuring that the key pointers are required and non-nullable
Resolves https://github.com/estuary/airbyte/issues/36
=> airbyte-to-flow: automatically fix key requirements in document schema

airbyte-to-flow/src/connector_runner.rs, airbyte-to-flow/src/libs/command.rs, airbyte-to-flow/src/main.rs
This is, I believe, the last missing piece before we're able to modify the log level in a shard spec (`flowctl-admin shards edit`) and have that take effect in the connector itself.
However, while the connectors we've written all support the flag `--log.level` we probably don't want to assume that any arbitary connector supports it. So instead of providing the underlying connector entrypoint with a `--log.level` flag this PR instead sets the `LOG_LEVEL` environment variable on the subprocess execution.
Since our boilerplate package `flow/protocols/airbyte` already supports environment variables as well as flags this should work as an opt-in mechanism without breaking anything that doesn't currently support it.
=> airbyte-to-flow: Plumb `--log.level` flag to `LOG_LEVEL` env var

airbyte-integrations/connectors/source-bing-ads/oauth2.patch.json, airbyte-integrations/connectors/source-facebook-marketing/oauth2.patch.json, airbyte-integrations/connectors/source-github/oauth2.patch.json, airbyte-integrations/connectors/source-google-ads/oauth2.patch.json, airbyte-integrations/connectors/source-google-analytics-data-api/oauth2.patch.json, airbyte-integrations/connectors/source-google-analytics-v4/oauth2.patch.json, airbyte-integrations/connectors/source-google-search-console/oauth2.patch.json, airbyte-integrations/connectors/source-google-sheets/oauth2.patch.json, airbyte-integrations/connectors/source-hubspot/oauth2.patch.json, airbyte-integrations/connectors/source-intercom/oauth2.patch.json, airbyte-integrations/connectors/source-linkedin-ads/oauth2.patch.json, airbyte-integrations/connectors/source-mailchimp/oauth2.patch.json, airbyte-integrations/connectors/source-notion/oauth2.patch.json, airbyte-integrations/connectors/source-surveymonkey/oauth2.patch.json, airbyte-integrations/connectors/source-tiktok-marketing/oauth2.patch.json
Using triple-braces which do not HTML-escape their value in mustache and handlebars. With Handlebars we have been using a global option to turn off this HTML-escaping, but with mustache there doesn't seem to be this option so we are going to use triple-braces.
=> oauth: use triple-braces in templates

airbyte-integrations/connectors/source-amazon-ads/.dockerignore, airbyte-integrations/connectors/source-amazon-ads/Dockerfile, airbyte-integrations/connectors/source-amazon-ads/spec.patch.json, airbyte-integrations/connectors/source-bing-ads/spec.patch.json, airbyte-integrations/connectors/source-exchange-rates/spec.patch.json, airbyte-integrations/connectors/source-facebook-marketing/spec.patch.json, airbyte-integrations/connectors/source-github/spec.patch.json, airbyte-integrations/connectors/source-google-ads/spec.patch.json, airbyte-integrations/connectors/source-google-analytics-v4/spec.patch.json, airbyte-integrations/connectors/source-google-search-console/spec.patch.json, airbyte-integrations/connectors/source-hubspot/spec.patch.json, airbyte-integrations/connectors/source-notion/spec.patch.json, airbyte-integrations/connectors/source-stripe/Dockerfile, airbyte-integrations/connectors/source-stripe/spec.patch.json, airbyte-integrations/connectors/source-tiktok-marketing/spec.patch.json
Includes suggested updates to spec descriptions across various connectors for readability and improved UX. 
Mostly these are:
* Adding branded shortlinks
* Removing HTML
* Punctuation, capitalization, and grammar changes
(I recently updated the [guide in the connectors repo](https://github.com/estuary/connectors/blob/main/config_schema_guidelines.md) to include more structured guidelines around description going forward). 
**A few more recommended changes** (Didn't do these because these connectors don't have spec patch files and I wasn't feeling confident adding them):
SOURCE-AMAZON-ADS
* Region: replace link with https://go.estuary.dev/8Ra66M
* Start date: recommend rewording as “Date from which to start collecting reports, in YYYY-MM-DD format. Shouldn’t be more than 60 days in the …
=> spec description updates (various)

airbyte-integrations/connectors/source-facebook-marketing/streams/activities.patch.json, airbyte-integrations/connectors/source-facebook-marketing/streams/ad_account.patch.json, airbyte-integrations/connectors/source-facebook-marketing/streams/ad_creatives.patch.json, airbyte-integrations/connectors/source-facebook-marketing/streams/ad_sets.patch.json, airbyte-integrations/connectors/source-facebook-marketing/streams/ads.patch.json, airbyte-integrations/connectors/source-facebook-marketing/streams/ads_insights.patch.json, airbyte-integrations/connectors/source-facebook-marketing/streams/campaigns.patch.json, airbyte-integrations/connectors/source-facebook-marketing/streams/custom_conversions.patch.json, airbyte-integrations/connectors/source-facebook-marketing/streams/images.patch.json, airbyte-integrations/connectors/source-facebook-marketing/streams/videos.patch.json
Facebook uses ISO8601, but JSONSchema's date-time requires RFC3339 and they are not compatible.
=> facebook: remove all format: date-time from facebook streams

airbyte-integrations/connectors/source-facebook-marketing/spec.patch.json, airbyte-integrations/connectors/source-github/spec.patch.json, airbyte-integrations/connectors/source-google-analytics-v4/spec.patch.json, airbyte-integrations/connectors/source-linkedin-ads/spec.patch.json, airbyte-integrations/connectors/source-tiktok-marketing/spec.patch.json
Updates facebook-marketing, github, google-analytics-v4, linkedin-ads, and tiktok-marketing to include "credentials" in their list of required fields since credentials are required for these connectors to work.
I gave a brief consideration to handling for a new spec patching mechanism that would append arrays rather than overwriting them, but that felt like a bit of overkill at the moment. Such a thing would not cleanly address cases where we _don't_ want all of the fields that the base airbyte connector says are reported & need to override those anyway, such as the case with `source-facebook-marketing`, so there'd still need to be a bit of ugliness to it.
=> source-*: make credentials required for connectors that need it

airbyte-to-flow/Cargo.lock, airbyte-to-flow/Cargo.toml, airbyte-to-flow/src/interceptors/airbyte_source_interceptor.rs, airbyte-to-flow/src/interceptors/mod.rs, airbyte-to-flow/src/interceptors/normalize.rs, airbyte-to-flow/src/libs/airbyte_catalog.rs
This is a fairly quick-and-dirty fix to hubspot captures having the field `hs_latest_source_timestamp` coming through looking like a `date-time` instead of a `date`, which breaks existing captures using the `format: date` in their schema for this field.
It adds processing to normalize this specific field, attempting to extract the equivalent `date` value from the `date-time`-ish string if it is present.
Future work should be more intelligent about this and use the collection schema, but for now I have it hard coded to handle the field `hs_latest_source_timestamp` to unblock existing captures.
Note that the first commit is entirely changes from `rustfmt` on `airbyte-source-interceptor.rs`. The meaningful modifications occur in the second commit, df455ad.
=> airbyte-to-flow: normalize hs_latest_source_timestamp

airbyte-to-flow/src/interceptors/normalize.rs
It turns out that documents generated by hubspot have their properties actually within an object with the key "properties".
=> airbyte-to-flow: hs_latest_source_timestamp normalization must be under "properties"

airbyte-to-flow/src/connector_runner.rs, airbyte-to-flow/src/errors.rs
Some airbyte connectors hang, it's a known issue: https://github.com/airbytehq/airbyte/issues/14499
Airbyte's solution to this seems to be restarting idle connectors. Here I'm implementing a similar logic that we restart idle connectors after 10 minutes of inactivity.
=> airbyte-to-flow: restart idle connectors

airbyte-integrations/connectors/source-notion/spec.patch.json
Remove date picker and add default value for start date to help user understand the date formatting requirement.
=> fix notion connector start date field

.github/workflows/connectors.yml, airbyte-integrations/connectors/source-amazon-ads/Dockerfile, airbyte-integrations/connectors/source-amplitude/Dockerfile, airbyte-integrations/connectors/source-bing-ads/Dockerfile, airbyte-integrations/connectors/source-exchange-rates/Dockerfile, airbyte-integrations/connectors/source-facebook-marketing/Dockerfile, airbyte-integrations/connectors/source-github/Dockerfile, airbyte-integrations/connectors/source-google-ads/Dockerfile, airbyte-integrations/connectors/source-google-analytics-data-api/Dockerfile, airbyte-integrations/connectors/source-google-analytics-v4/Dockerfile, airbyte-integrations/connectors/source-google-search-console/Dockerfile, airbyte-integrations/connectors/source-google-sheets/Dockerfile, airbyte-integrations/connectors/source-hubspot/Dockerfile, airbyte-integrations/connectors/source-intercom/Dockerfile, airbyte-integrations/connectors/source-linkedin-ads/Dockerfile, airbyte-integrations/connectors/source-mailchimp/Dockerfile, airbyte-integrations/connectors/source-notion/Dockerfile, airbyte-integrations/connectors/source-salesforce/Dockerfile, airbyte-integrations/connectors/source-slack/Dockerfile, airbyte-integrations/connectors/source-stripe/Dockerfile, airbyte-integrations/connectors/source-surveymonkey/Dockerfile, airbyte-integrations/connectors/source-tiktok-marketing/Dockerfile, airbyte-to-flow/src/interceptors/airbyte_source_interceptor.rs, airbyte-to-flow/src/interceptors/fix_document_schema.rs
- Remove airbyte's recently introduced nonstandard JSONSchema attributes such as `group`, `airbyte_hidden` and `airbyte_type`
- Updated CI so that when working on a pull-request, connectors built in the pull-request will use the `airbyte-to-flow` version from the same branch to help with testing.
=> airbyte-to-flow: add normalization to remove nonstandard jsonschema

airbyte-integrations/connectors/source-chargebee/streams/attached_item.patch.json, airbyte-to-flow/src/interceptors/airbyte_source_interceptor.rs, airbyte-to-flow/src/interceptors/fix_document_schema.rs
- move logic for traversing a jsonschema document to `traverse_jsonschema` and use it to write a new normalization: `remove_enums`
=> remove enums

airbyte-integrations/connectors/source-snapchat-marketing/oauth2.patch.json, airbyte-to-flow/Cargo.lock, airbyte-to-flow/Cargo.toml, airbyte-to-flow/src/interceptors/airbyte_source_interceptor.rs, airbyte-to-flow/src/interceptors/fix_document_schema.rs, airbyte-to-flow/src/interceptors/normalize.rs
- Update `traverse_jsonschema` to supply the pointer of the schema property we are on
- Add a new normalization which ensures date-time properties are RFC3339, with a test case that checks whether this would resolve #132 
- Note, at the moment this doesn't work for items inside an array because I haven't yet implemented a way for us to match pointer of array items to array items, we can revisit that later if we need to
=> Automatic normalizations

airbyte-to-flow/src/connector_runner.rs, airbyte-to-flow/src/errors.rs, airbyte-to-flow/src/interceptors/fix_document_schema.rs, airbyte-to-flow/src/libs/stream.rs
renaming "airbyte-to-flow" to "atf" in our logs
=> remove mentions of "airbyte" in messages to user

airbyte-integrations/connectors/source-stripe/streams/customers.patch.json, airbyte-integrations/connectors/source-stripe/streams/subscription_schedule.patch.json
A couple of schema patches for `source-stripe` based on data we have seen from a running capture.
=> source-stripe: schema patches

airbyte-integrations/connectors/source-notion/Dockerfile, airbyte-integrations/connectors/source-notion/streams/blocks.patch.json, airbyte-integrations/connectors/source-notion/streams/pages.patch.json
Schema updates for source-notion seem to have been accidentally lost at some point. This attempts to add those back as patches. Unfortunately, many of the patches are within an array, which requires copying over the complete array contents. Additionally, I had to copy over all the shared schemas that were `$ref`'d so that they're now inlined, because the patches seem to be applied after refs are resolved.
Lastly, the `blocks` schema was updated to make the `type` and `object` properties plain `string`s rather than `enum`s. Airbyte-to-flow removes any `enum` restrictions, so without `type: string` the schemas for thos properties would be completely empty.
=> source-notion: re-add schema patches

airbyte-integrations/connectors/source-notion/streams/databases.patch.json
Updates the schema for the 'databases' stream to have a less restrictive enumeration of possible values.
=> source-notion: fix databases schema

airbyte-to-flow/src/errors.rs, airbyte-to-flow/src/libs/command.rs, airbyte-to-flow/src/main.rs
See discussion here: https://github.com/estuary/airbyte/issues/193
=> atf: plumb through exit code transparently (no error message)

airbyte-integrations/connectors/source-surveymonkey/spec.map.json
This patch isn't needed anymore, since the airbyte connector actually wants the access token to be at `/credentials/access_token`.
Tested this with `flowctl raw discover` & `flowctl raw capture`.
=> source-surveymonkey: fix oauth

airbyte-integrations/connectors/source-stripe/Dockerfile, airbyte-integrations/connectors/source-stripe/streams/subscription_schedule.patch.json, airbyte-to-flow/src/interceptors/fix_document_schema.rs, airbyte-to-flow/src/interceptors/normalize.rs
- Update `normalize_to_rfc3339` so it also checks for integer values and considers them as Unix seconds timestamps (we can later add support for other Unix timestamps). This happens if the field is marked as `format: "date-time"`, but has a numeric value.
- Update `automatic_normalizations` function so that it can handle normalization of array items as well. The implementation here is pretty gross. Ideally this should be refactored into `traverse_jsonschema`, I attempted to do that, but there was some challenge there with the fact that it becomes hard to reason about ownership of `doc` if both `traverse_jsonschema` itself and the closure passed to want to hold a reference to `doc`. So for now I've settled on this implementation.
=> atf: unix to datetime normalization, array items normalization

airbyte-integrations/connectors/source-salesforce/schema_normalizations.json, airbyte-to-flow/src/interceptors/airbyte_source_interceptor.rs, airbyte-to-flow/src/interceptors/fix_document_schema.rs
Salesforce connector outputs `format: "date"` for some fields, but all fields in Salesforce are represented as `date-time`, and we frequently run into this issue.
This PR allows for us to specify some schema normalizations to be enabled for specific connectors through a new config file. I'm enabling this normalization for salesforce which replaces all `format: "date"` with `format: "date-time"`
=> atf: schema normalizations, date to datetime for salesforce

.github/workflows/connectors.yml
to speed up build process:
- only build atf if its files have been changed
- if files have changed, we will build atf and use that newly built atf when building the connectors
- otherwise we just build the connectors with `:dev` tag of atf
=> ci: only build atf if updated

airbyte-to-flow/src/libs/airbyte_catalog.rs, airbyte-to-flow/src/libs/stream.rs
Airbyte has introduced a new type of message `TRACE`, adding preliminary support for it here.
=> airbyte-to-flow: support airbyte's new TRACE messages

airbyte-integrations/connectors/source-salesforce/Dockerfile
Use airbyte salesforce 2.0.7, since anything after 2.0.9 has been shown to miss data, and there is no published image for 2.0.8.
=> source-salesforce: use older airbyte image

airbyte-integrations/connectors/source-salesforce/streams/*.patch.json, airbyte-to-flow/src/interceptors/airbyte_source_interceptor.rs
- add support for reading wildcard patch files `*.patch.json`
- add a wildcard patch file for salesforce to add reduction strategy to the connector (this helps when using it beside the real-time connector)
=> atf: support wildcard schema patches, apply one for salesforce reduction

airbyte-integrations/connectors/source-amazon-ads/streams/attribution_report_performance_campaign.pk.json
removed "adGroupId" and "publisher" attribution_report_performance_campaign.pk.json
=> Removed unnecessary keys from Amazon Ads Attribution Report

airbyte-to-flow/src/interceptors/normalize.rs
- It seems [`parse_with_timezone`](https://docs.rs/dateparser/latest/dateparser/fn.parse_with_timezone.html) assumes the current local time if no time is available when parsing a naive date
- The change here sets the time to `00:00:00` if no time is given.
- Tested using our unit tests for this section
=> airbyte-to-flow: normalizing dates to date-time must use 00:00:00

airbyte-to-flow/src/interceptors/fix_document_schema.rs
We have run into this issue multiple times where a connector emits a schema with a `format` that is not supported by us, so the schema fails validation. Here I'm using the actual flow `json` crate to verify that the given `format` value is supported by us, if it is not, then we remove it.
Tested using the unit tests.
=> atf: filter out unsupported `format` values

airbyte-integrations/connectors/source-airtable/Dockerfile, airbyte-integrations/connectors/source-airtable/spec.patch.json
OAuth2.0 has been removed from source-airtable connector as it was showing 400 error after the token expires.
=> source-airtable: OAuth2.0 removed

.github/workflows/connectors.yml, airbyte-integrations/connectors/source-google-sheets/Dockerfile, airbyte-to-flow/src/connector_runner.rs, airbyte-to-flow/src/errors.rs, airbyte-to-flow/src/libs/command.rs, airbyte-to-flow/src/libs/stream.rs, airbyte-to-flow/src/main.rs, local-build.sh, tools/bin/build_image.sh
- This removes some of the noise that would obscure the actual error from the connector. Tested with google sheets and the output of this connector becomes this:
```
$ flowctl raw discover ghcr.io/estuary/source-google-sheets:21e4a87 acmeCo
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{"ts":"2023-10-27T12:29:06.847252138+00:00","level":"info","message":"connector-init started","fields":{"log_level":"info","module":"connector_init","port":49092}}
{"ts":"2023-10-27T12:29:09.882460709+00:00","level":"info","message":"Running discovery on sheet blah"}
{"ts":"2023-10-27T12:29:10.373776042+00:00","level":"error","message":"Giving up get(...) after 1 tries (googleapiclient.errors.HttpError: …
```
=> atf: cleanup error outputs

airbyte-to-flow/src/interceptors/fix_document_schema.rs
The change from `from_value` to `from_str` was made since we thought they are equivalent, but they are not, as `from_str` requires a wrapped string. This was causing all `format` stanzas to be removed.
See https://github.com/estuary/airbyte/pull/275#discussion_r1372341249 for context
=> fix nonstandard format filtering

airbyte-to-flow/src/connector_runner.rs
This fixes an issue that was seen in production where the output of airbyte-to-flow could not be parsed as JSON.  The source of the issue seems likely to be that ATF is calling `write` instead of `write_all` when it writes the responses to stdout (the return value of `write` was ignored).
=> airbyte-to-flow: use write_all instead of write for responses

airbyte-integrations/connectors/source-airtable/Dockerfile
The image tag that was used in the Dockerfile was incorrect, and resulted in failure to build the image. I'm assuming the version components were just accidentally transposed, so I updated it to `3.0.1` instead of the latest version.
=> source-airtable: update tag of source image to one that exists

airbyte-to-flow/src/connector_runner.rs
It can be larger than the desired duration.
=> atf: use saturating_sub when subtracting elapsed duration

airbyte-integrations/connectors/source-google-analytics-data-api/Dockerfile, airbyte-integrations/connectors/source-google-analytics-v4/Dockerfile
Goes along with estuary/flow#1403 and estuary/connectors#1321
=> make source-google-analytics connectors free to use on estuary

airbyte-integrations/connectors/source-jira/Dockerfile
Upgrading Jira version to Airbyte latest. Confirmed that upgrade will ignore boards that do not have sprints configured instead of exiting the connector.
New Streams:
- Issue custom field options
- IssueTypes
- Project Roles
=> Upgrade source-jira version

.github/workflows/connectors.yml, airbyte-to-flow/Cargo.lock, airbyte-to-flow/Cargo.toml, airbyte-to-flow/src/main.rs
Updates ATF to the latest Flow protocol from
https://github.com/estuary/flow/pull/1787, which includes information about array fields in projection inference.
See also https://github.com/estuary/airbyte/pull/321 where I did the same thing to update ATF for the addition of numeric inference.
=> atf: update to latest flow protocol

airbyte-integrations/connectors/source-greenhouse/omitted_streams.json, airbyte-to-flow/src/interceptors/airbyte_source_interceptor.rs
The `activity_feed` stream in `source-greenhouse` is an array API response that should be flattened, but the Airbyte connector emits it as-is. An abbreviated example response is below:
```json
{
"notes": [
{
"id": 1,
}
],
"emails": [
{
"id": 1,
}
],
"activities": [
{
"id": 1,
},
{
"id": 2,
}
]
}
```
The real solution is to fix the connector so individual objects from the response arrays are emitted instead of emitting the entire response as as single document. However, until the connector is fixed, omitting `activity_feed` from discovery is a temporary fix.
We previously had the capability to omit streams from discovery with `selected_streams.json`, but we changed it to specify streams that should be enabled & disabled everything else. To re-add the capability to completely omit streams …
=> support omitted streams

airbyte-integrations/connectors/source-greenhouse/streams/applications.patch.json
Patching the `applications` schema to address schema violations stopping a new production task.
There may need to be further patches for other streams (I suspect `source-greenhouse` has gotten much use before now), but these `applications` schema patches should allow the task to at least finish that stream.
=> source-greenhouse: patch applications schema

airbyte-integrations/connectors/source-bing-ads/Dockerfile
This version bump from 0.1.19 to 0.1.24 adds retries for temporary DNS resolution failures & a lookback window capability. Some fields are also added to a few streams, but none are removed so this this bump is backwards compatible.
=> source-bing-ads: bump to version 0.1.24

airbyte-integrations/connectors/source-marketo/selected_streams.json
We've observed issues with the the conditional discovery logic for all the `activity_foobar` bindings. It's not reliable, so sometimes these bindings are discovered and sometimes they aren't. If these bindings disappear when they were disabled then are re-discovered later as enabled, that could blow up certain API limits. To avoid that, I'm choosing to only enable the bindings that are consistently discovered, and the remaining conditionally discovered bindings are disabled.
Tested on a local stack and confirmed that all the `activity_foobar` bindings are discovered as disabled.
=> source-marketo: limit which streams are enabled after discovery

airbyte-integrations/connectors/source-google-sheets/google_sheets_source/google_sheets_source.py, airbyte-integrations/connectors/source-google-sheets/google_sheets_source/helpers.py, airbyte-integrations/connectors/source-google-sheets/unit_tests/test_helpers.py
Captures have started hitting `KeyError`s because the `properties` field is missing on the stream's JSON schema. I haven't been able to replicate this locally, so this logging is suppose to help figure out what that dictionary looks like for captures hitting the error.
=> source-google-sheets: add debug logs to troubleshoot missing `properties` field

airbyte-integrations/connectors/source-google-sheets/google_sheets_source/helpers.py
For some reason, debug logging isn't showing up when setting `shards: {"logLevel": "debug"}` on captures. For the sake of just getting something logged quickly, I'm changing these to info level logs while I troubleshoot.
=> source-google-sheets: switch to info level logging

airbyte-integrations/connectors/source-google-sheets/google_sheets_source/helpers.py
Commit [1b7eff0e5ecf774ee84f773caa6bda213afa21f8 in estuary/flow](https://github.com/estuary/flow/commit/1b7eff0e5ecf774ee84f773caa6bda213afa21f8) changed where properties live within the JSON schema. `source-google-sheets` needs to look in the new location for properties, otherwise the connector will crash with a `KeyError`.
For reference, this is what `stream.json_schema` looks like in `parse_sheet_and_column_names_from_catalog`:
```json
{
"$defs": {
"flow://connector-schema": {
"$id": "flow://connector-schema",
"$schema": "http://json-schema.org/draft-07/schema#",
"properties": {
"my_field": {
"type": "string"
},
"another_field": {
"type": "string"
},
"row_id": {
"type": "integer"
}
},
"required": [
"row_id"
],
"type": "object"
}
},
"$ref": "flow://connector-schema"
}
```
=> source-google-sheets: update properties location in JSON schema
